# a very aggressive watchtower config, useful when deploying in a headless environment
services:
  watchtower:
    image: docker.io/containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /root/.docker/config.json:/config.json # enable only if you need it
    command: --cleanup --include-restarting --include-stopped --revive-stopped --label-enable
